### ISSUE TITLE
The uploaded results could not be evaluated. Check for format errors.

### ISSUE THREAD

**Issue by Pharaon23** [KuanchihHuang/MoMA-M3T#4]

**Comment by KuanchihHuang** [comment]
Hi, can you provide more detailed errors? 
The script contains inference and evaluation parts, and you can comment out the evaluation part temporally 
to make sure the inference work well.

**Comment by zhangsirui-sir** [comment]
Dear author, I encountered the following error when reproducing your evaluation results

**Comment by zhangsirui-sir** [comment]
Dear author, I encountered the following error when reproducing your evaluation results about KITTI datasets:

Traceback (most recent call last):
  File "/home/dell/zsr/MoMA-M3T-main/ab3dmot_kitti/scripts/KITTI/evaluate1.py", line 1235, in <module>
    success = evaluate('moma',mail,1,True,False,0.25)
  File "/home/dell/zsr/MoMA-M3T-main/ab3dmot_kitti/scripts/KITTI/evaluate1.py", line 1139, in evaluate
    e = trackingEvaluation(t_sha=result_sha, mail=mail,cls=c,eval_3diou=eval_3diou,eval_2diou=eval_2diou,num_hypo=num_hypo,thres=thres)
  File "/home/dell/zsr/MoMA-M3T-main/ab3dmot_kitti/scripts/KITTI/evaluate1.py", line 119, in __init__
    with open(filename_test_mapping, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: './scripts/KITTI/evaluate_tracking.seqmap.val'
Processing Result for KITTI 3D MOT Benchmark
The following './scripts/KITTI/evaluate_tracking.seqmap.val' file was not found. I carefully checked the inference code and found that this sequence file was not generated.If it was copied from the AB3DMOT model, the following error would be reported：

The uploaded results could not be evaluated. Check for format errors.

So I would like to ask how to solve this problem. I would be grateful if you can reply in time.

**Comment by KuanchihHuang** [comment]
@zhangsirui-sir 
Sorry for the late reply. 
We upload the missing files.
